config/routes.rb
Tracker::Application.routes.draw do
  resources :tasks do
    member do
      post :claim
    end
  end
  post 'tasks/:id/:state_transition' => 'tasks#state_transition', as: :state_transition

  resources :users


  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  root 'tasks#index'
end

app/models/action.rb
class Action < ActiveRecord::Base
  belongs_to :resulting_state, :class_name => 'State'
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
  belongs_to :task
  belongs_to :user, :class_name => 'User', :foreign_key => :user_id
end

app/models/state.rb
class State < ActiveRecord::Base
  serialize :next_action_ids

  def next_actions
    @next_actions ||= Action.where(:id => next_action_ids)
  end

  def reload
    super
    @next_actions = nil
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :author, :class_name => 'User'
  belongs_to :template
  belongs_to :super_task, :class_name => 'Task'
  has_many :sub_tasks, :class_name => 'Task', :foreign_key => :super_task_id
  has_many :ownerships
  has_many :sub_templates, :class_name => 'Template', :foreign_key => :parent_task_id
  has_many :owners, :through => :ownerships, :source => :user

  delegate :next_actions, :to => :current_state

  belongs_to :state

  def add_owner(user)
    Ownership.create(:user => user, :task => self)
  end

  def max_points
    4
  end

  def current_state
    state || template.initial_state
  end

  def all_sub_templates
    sub_templates + Template.where(:parent_task_id => nil)
  end
end

app/models/template.rb
class Template < ActiveRecord::Base
  belongs_to :parent_task, :class_name => 'Task'
  belongs_to  :initial_state, :class_name => 'State'
  serialize :options

  def initialize(attributes)
    super
    self.options ||= {}
  end

  def has_acceptance_criteria?
    !!self.options[:acceptance_criteira]
  end

  def possible_states
    states = []
    next_states = [initial_state]
    while next_states.present?
      states += next_states
      next_states = next_states.map(&:next_actions).flatten.map(&:resulting_state).flatten.compact.uniq.reject { |state| states.include?(state) }
    end

    states
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :root_task, :class_name => 'Task', :foreign_key => 'author_id'
  has_many :authored_tasks, :class_name => 'Task', :foreign_key => 'author_id'
  has_many :ownerships
  has_many :favorites
  has_many :owned_tasks, :through => :ownerships, :source => :task
  has_many :favorited_tasks, :through => :favorites, :source => :task

  def name
    display_name || "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    User.first
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy, :state_transition, :claim]

  def index
    current_user.root_task
    tasks = Task.where(:super_task_id => current_user.root_task).order(:index)
    render :index, :locals => { :tasks => tasks, :current_task => nil, :super_task => current_user.root_task }
  end

  def show
    task = Task.find(params[:id])
    if !task.super_task
      redirect_to tasks_path
      return
    end

    sibling_tasks = task.super_task.sub_tasks.order(:index)
    super_task = task.super_task

    render :index, :locals => { :tasks => sibling_tasks, :current_task => task, :super_task => super_task }
  end

  # GET /tasks/new
  def new
    super_task = Task.find(params[:super_task_id])
    @task = Task.new(:author => current_user, :super_task => super_task, :template => super_task.all_sub_templates.first)
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  def state_transition
    next_action = @task.next_actions.detect { |action| action.name == params[:state_transition] }
    if next_action
      @task.update(:state => next_action.resulting_state)
      flash[:notice] = "Task #{@task.state.name}"
      redirect_to task_path(@task)
    else
      flash[:error] = "You can't go to the state."
      redirect_to :back
    end
  end

  def claim
    if @task.add_owner(current_user)
      flash[:notice] = "Ownership added"
    else
      flash[:notice] = "There was an issue adding ownership."
    end
    redirect_to task_path(@task)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:author_id, :type_id, :notes, :status_id, :index, :points)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :display_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    {
      :notice => 'alert-success',
      :error  => 'alert-danger',
      :alert  => 'alert-info'
    }[level]
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Tracker
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    -#= render 'shared/nav'
    .container-fluid
      = render 'shared/flash_messages'
      .row-fluid
        .span2
          = render 'shared/sidebar'
        .span10
          = yield
  %hr/
  %footer
    %p © Dean 2013

app/views/shared/_flash_messages.html.haml
- [:notice, :error, :alert].each do |level|
  - unless flash[level].blank?
    .alert(class="#{flash_class(level)}")
      %a.close(href='#') x
      %p= flash[level]

app/views/shared/_nav.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container-fluid
      %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand{:href => "#"} Project name
      .nav-collapse.collapse
        %p.navbar-text.pull-right
          Logged in as
          %a.navbar-link{:href => "#"} Username
        %ul.nav
          %li.active
            %a{:href => "#"} Home
          %li
            %a{:href => "#about"} About
          %li
            %a{:href => "#contact"} Contact
      / /.nav-collapse

app/views/shared/_sidebar.html.haml
.well.sidebar-nav
  %h3 Tracker
  %ul.nav.nav-list
    %li.nav-header Favorites
    - current_user.favorited_tasks.limit(10).each do |task|
      %li
        %a{:href => task_path(task)}= task.title.truncate(12)
    %li.nav-header Owner On
    - current_user.owned_tasks.limit(10).each do |task|
      %li
        %a{:href => task_path(task)}= task.title.truncate(12)
    %li.nav-header Author of
    - current_user.authored_tasks.limit(10).select{ |t| t.super_task.present? }.each do |task|
      %li
        %a{:href => task_path(task)}= task.title.truncate(12)

app/views/tasks/_brief.html.haml
.task.brief.well.well-small{:class => defined?(active) && active ? 'active' : nil}
  %h4
    %i{:class =>"icon-#{task.template.icon}"}
    = link_to task.title, task
  - owners = task.owners
  %p.pull-left= owners.present? ? owners.map(&:name).join(', ') : 'Unclaimed'
  - if !owners.include?(current_user)
    %p.pull-left
      |
      = link_to 'Claim', claim_task_path(task), :method => :post
  .clearfix
  %p.pull-left
    - task.next_actions.each do |action|
      %a.btn(href="/tasks/#{task.id}/#{action.name}" data-method="post")= action.name
  %p.pull-right
    = task.current_state.name
    |
    - if task.points
      - task.points.times do
        %i.icon-star
      - (task.max_points - task.points).times do
        %i.icon-star-empty
    - else
      Unestimated
    = link_to '', task, :method => :delete, :class => 'icon-trash'
  .clearfix

app/views/tasks/_form.html.haml
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :author_id
    = @task.author.name
  .field
    = f.label :template_id
    - template_options = @task.super_task.all_sub_templates.map { |t| [t.name, t.id] }
    = f.select('template_id', template_options, {})
  .field
    = f.label :state_id
    - state_options = @task.template.possible_states.map { |s| [s.name, s.id] }
    = f.select('state_id', state_options, {})
  .field
    = f.label :notes
    = f.text_area :notes
  -if @task.template.has_acceptance_criteria?
    .field
      = f.label :acceptance_criteria
      = f.text_area :acceptance_criteria
  .field
    = f.label :points
    = f.number_field :points
  .actions
    = f.submit 'Save'

app/views/tasks/_full.html.haml
%p
  %h4= task.title
%p
  %b Author:
  = task.author.name
%p
  %i{:class =>"icon-#{task.template.icon}"}
  = task.template.name
%p
  %b Notes:
  = task.notes
- if task.template.has_acceptance_criteria?
  %p
    %b AC:
    = task.acceptance_criteria
%p
  %b State:
  = task.current_state.name
%p
  %b Points:
  = task.points
%p
  %b Tasks:
  - task.sub_tasks.each do |sub_task|
    = render :partial => 'tasks/brief', :locals => {:task => sub_task}

= link_to 'Edit', edit_task_path(task)
\|
= link_to 'Back', tasks_path

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h3
  %a{:href => task_path(super_task)}= super_task.title

.span5
  %ul#sortable.unstyled
    - tasks.each do |task|
      %li= render :partial => 'tasks/brief', :locals => {:task => task, :active => current_task == task}
.span5
  - if current_task
    = render :partial => 'tasks/full', :locals => {:task => current_task}
  - else
    Pick a task from the left!


%br

= link_to 'New Task', new_task_path(:params => {:super_task_id => super_task.id})

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p
  %h4= task.title
%p
  %b Author:
  = task.author.name
%p
  %i{:class =>"icon-#{task.template.icon}"}
  = task.template.name
%p
  %b Notes:
  = task.notes
%p
  %b State:
  = task.state.name
%p
  %b Points:
  = task.points
%p
  %b Tasks:
  - task.sub_tasks.each do |sub_task|
    = render :partial => 'tasks/brief', :locals => {:task => sub_task}



= link_to 'Edit', edit_task_path(task)
\|
= link_to 'Back', tasks_path

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br>
    <%= f.text_field :display_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.haml
%h1 Listing users
%table
  %thead
    %tr
      %th First name
      %th Last name
      %th Display name
      %th
      %th
      %th
  %tbody
    - @users.each do |user|
      %tr
        %td= user.first_name
        %td= user.last_name
        %td= user.display_name
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Display name:</strong>
  <%= @user.display_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>